import {
  ArrowLeftRight,
  BarChart,
  Banknote,
  Bitcoin,
  Book,
  Briefcase,
  Building2,
  Car,
  Coins,
  CreditCard,
  Gem,
  Gift,
  Heart,
  Home,
  Landmark,
  MoreHorizontal,
  PiggyBank,
  ShoppingBag,
  Smartphone,
  Tag,
  TrendingUp,
  Tv,
  Utensils,
  Wallet,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  'arrow-left-right': ArrowLeftRight,
  'bar-chart': BarChart,
  'banknote': Banknote,
  'bitcoin': Bitcoin,
  'book': Book,
  'briefcase': Briefcase,
  'building-2': Building2,
  'car': Car,
  'coins': Coins,
  'credit-card': CreditCard,
  'gem': Gem,
  'gift': Gift,
  'heart': Heart,
  'home': Home,
  'landmark': Landmark,
  'more-horizontal': MoreHorizontal,
  'piggy-bank': PiggyBank,
  'shopping-bag': ShoppingBag,
  'smartphone': Smartphone,
  'tag': Tag,
  'trending-up': TrendingUp,
  'tv': Tv,
  'utensils': Utensils,
  'wallet': Wallet,
  'zap': Zap,
}

export function CategoryIcon({ icon, className }: { icon: string; className?: string }) {
  const Icon = CATEGORY_ICON_MAP[icon] ?? Tag
  return <Icon className={className} />
}
